### PR TITLE
Partial Chinese translation and language switching UI

### PR DESCRIPTION
**Pull request by gvidon**
* Adds a partial Chinese translation on the main page
  * Originally submitted in #8 
* Adds a language switching UI
  * Only available on the main page, as this is the only multi-language page on the website
* Also adds an auto redirect to Chinese version of the main page for Chinese users.
   
image

### CODE REVIEW

**Review by qmonnet — COMMENTED** [review]
From what I see on the preview it looks good. I confirm that:
- Language selection works
- Other pages are still available (not translated) from Chinese version
- Going to another page and coming back to home page keeps language choice

Not tested:
- Auto-redirect for Chinese users, not sure how to test
- Content in Chinese, I can't read the language

Thanks for the fix on the style for the selector.

Note that this PR currently has conflicts with the `master` branch (related to the redirect `news`->`blog` it seems), that needs to be addressed before this can be merged.

Great work!

**Comment by gvidon** [comment]
@qmonnet thank you for the feedback! The merge conflict has been resolved.

**Review by qmonnet — APPROVED** [review]
Rebase looks good, thank you.

I validated the redirection for Chinese users, by changing the preferred language for content in my browser. It works if I select only `zh-CH` (`Accept-Language: zh-CN`), not if I accept several ones (`Accept-Language: zh-CN,zh-HK;q=0.5` or any other mix), but I don't suppose this is a concern.

I can't review the content in Chinese.

**Comment by qmonnet** [comment]
With some help from Google translate, I had a look at the translation, and it all looks fine (https://translate.google.com/translate?hl=en&sl=auto&tl=en&u=https%3A%2F%2Fdeploy-preview-96--ebpfio.netlify.app%2Fzh-cn%2F).

**Pull request merged**
