### PR TITLE
Improve Chinese version of the index page

### PR DESCRIPTION
**Pull request by ArthurChiao**
Signed-off-by: arthurchiao <arthurchiao@hotmail.com>

### CODE REVIEW

**Comment by ArthurChiao** [comment]
@qmonnet FYI.

**Review by qmonnet — CHANGES_REQUESTED** [review]
Thanks a lot! I'm not able to comment on the improvements, but I trust your judgement.

A few comments:
- The language selector at the top of the page says `Chinese`, written in English, could we maybe rewrite that in Chinese? This is set at two locations in src/layout/index.js.
- The translation is missing for the title “Latest Blog Post” ([here](https://github.com/cilium/ebpf.io/blob/4a5e42107a66da80f99664dae2bc22759f586531/src/pages/index.zh-cn.js#L178)). This is because the section was added after the creation of the PR adding Chinese translation. Could you please translate that, too?

Not sure why we don't have the Netlify preview, let's see if it comes back after addressing those nits.

**Review by ArthurChiao — COMMENTED** [review]
Comments resolved.

**Review by qmonnet — APPROVED** [review]
Looks good, as far as I can tell :) Thanks!

**Comment by ArthurChiao** [comment]
Hi @qmonnet , seems something got broken, anything I can help?

**Comment by qmonnet** [comment]
@ArthurChiao Nothing broken, I went through the list of PRs that were waiting for manual approval for the preview on Netlify and tried to clean up those corresponding to PRs already closed (since there's no point in generating the preview now). I didn't realise Netlify would add a comment here and that you would get a notification, sorry about that. Everything's good :).

**Pull request merged**
